version: '3.8'

services:
  mongo-database:
    image: mongo:latest
    container_name: postcode-mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  api:
    build:
      dockerfile: Dockerfile
      context: "."
    depends_on:
      - mongo-database
    volumes:
      - /api/node_modules
      - ./src:/api
    ports:
      - '3000:3000'
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mongo-database
      DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo-database:27017
      PORT: 3000
    container_name: api

